language: elixir
services:
  - redis-server
elixir:
  - 1.3.4
  - 1.4.4
otp_release:
  - 19.2
env:
  - MIX_ENV=test
script: mix coveralls.travis
before_install:
  - cp config/dev.dist.exs config/dev.exs
  - mysql -e 'CREATE DATABASE grafikart_dev;'
  - echo "USE mysql;\nUPDATE user SET password=PASSWORD('root') WHERE user='root';\nFLUSH PRIVILEGES;\n" | mysql -u root
